image:
  repository:
  registry:
  pullPolicy: IfNotPresent
  flask:
    image: flask
    tag:

imagePullSecrets: []
nameOverride: ""
fullNameOverride: ""

ingress:
  host:
  tls:
    enabled: false
    clusterIssuer:
    secretName:

dataVisualizer:
  flask:
    pvcSize: 5Gi
