apiVersion: v1
kind: Service
metadata:
  name: {{ include "data-visualizer.fullname" . }}-flask
  labels:
    {{- include "data-visualizer.flask.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "data-visualizer.flask.selectorLabels" . | nindent 4 }}