apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "data-visualizer.fullname" . }}-flask-data
  labels:
    {{- include "data-visualizer.flask.labels" . | nindent 4 }}
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.dataVisualizer.flask.pvcSize }}